#pragma once

#include <optional>
#include <string>

namespace ccmcp::storage {

// IRuntimeSnapshotStore persists and retrieves the runtime configuration snapshot
// emitted once per process launch.
//
// Snapshots are append-only: save() inserts a new row keyed by run_id.
// A run_id is always unique (generated by IIdGenerator) so conflicts do not occur
// in normal operation.
class IRuntimeSnapshotStore {
 public:
  virtual ~IRuntimeSnapshotStore() = default;

  // Insert a new runtime snapshot row.
  // run_id must be unique; snapshot_json is the serialized RuntimeConfigSnapshot;
  // snapshot_hash is the SHA-256 hex digest of snapshot_json;
  // created_at is an ISO 8601 timestamp.
  virtual void save(const std::string& run_id, const std::string& snapshot_json,
                    const std::string& snapshot_hash, const std::string& created_at) = 0;

  // Retrieve the snapshot_json for a given run_id. Returns nullopt if not found.
  [[nodiscard]] virtual std::optional<std::string> get_snapshot_json(
      const std::string& run_id) const = 0;

 protected:
  IRuntimeSnapshotStore() = default;
  IRuntimeSnapshotStore(const IRuntimeSnapshotStore&) = default;
  IRuntimeSnapshotStore& operator=(const IRuntimeSnapshotStore&) = default;
  IRuntimeSnapshotStore(IRuntimeSnapshotStore&&) = default;
  IRuntimeSnapshotStore& operator=(IRuntimeSnapshotStore&&) = default;
};

}  // namespace ccmcp::storage
